### ISSUE TITLE
Trying to export the onnx model reports an error

### ISSUE THREAD

**Issue by hjfdsssdg** [open-mmlab/mmfewshot#107]
Here are the specific error messages：
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 325, in <module>
    args.cfg_options)
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/core/export/pytorch2onnx.py", line 89, in build_model_from_cfg
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home、anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'FSCE is not in the models registry'
Here are the specific error messages

**Comment by wangzuo-hx** [comment]
Did you succeed in exporting the onnx model？ I also encountered the same error as you.

**Comment by hjfdsssdg** [comment]
> 
I didn't solve this either

**Comment by hjfdsssdg** [comment]
> I didn't solve this either
