### ISSUE TITLE
chamfer_distance_forward miss in module _ext

### ISSUE THREAD

**Issue by henbucuoshanghai** [open-mmlab/mmfewshot#112]
python ./tools/classification/train.py   configs/classification/baseline/cub/baseline_conv4_1xb64_cub_5way-1shot.py
No CUDA runtime is found, using CUDA_HOME=':/usr/local/cuda-11.1'
Traceback (most recent call last):
  File "./tools/classification/train.py", line 13, in <module>
    from mmcls.models import build_classifier
  File "/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcls/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcls/models/backbones/__init__.py", line 3, in <module>
    from .conformer import Conformer
  File "anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcls/models/backbones/conformer.py", line 9, in <module>
    from mmcv.cnn.bricks.transformer import AdaptivePadding
  File "/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/transformer.py", line 22, in <module>
    from mmcv.ops.multi_scale_deform_attn import \
  File "/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 10, in <module>
    from .chamfer_distance import chamfer_distance
  File "naconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/ops/chamfer_distance.py", line 12, in <module>
    '_ext', ['chamfer_distance_forward', 'chamfer_distance_backward'])
  File anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: chamfer_distance_forward miss in module _ext

**Comment by henbucuoshanghai** [comment]
my cuda is 11.1,ubuntu 18.04   ,sth is wrong?

**Comment by henbucuoshanghai** [comment]
torch is 1.12
