### ISSUE TITLE
运行mpsr第一阶段报错~

### ISSUE THREAD

**Issue by LiBiGo** [open-mmlab/mmfewshot#123]
Traceback (most recent call last):
  File "/root/mmfewshot/./tools/detection/train.py", line 236, in <module>
    main()
  File "/root/mmfewshot/./tools/detection/train.py", line 225, in main
    train_detector(
  File "/root/mmfewshot/mmfewshot/detection/apis/train.py", line 48, in train_detector
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/root/mmfewshot/mmfewshot/detection/apis/train.py", line 48, in <listcomp>
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/root/mmfewshot/mmfewshot/detection/datasets/builder.py", line 311, in build_dataloader
    data_loader = TwoBranchDataloader(
TypeError: __init__() got an unexpected keyword argument 'persistent_workers'
Killing subprocess 9272
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/pytorch1.8/bin/python', '-u', './tools/detection/train.py', '--local_rank=0', 'configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_base-training.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by guanlaoshi** [comment]
可以在mmfewshot/detection/datasets/builder.py 第311行左右添加如下代码：
```python
        # wrap two dataloaders with dataloader wrapper
        #----------20230321添加以下
        #由于会出现TypeError: __init__() got an unexpected keyword argument 'persistent_workers'
        #所以在这删掉persistent_workers关键对
        del kwargs['persistent_workers']
        # ----------20230321添加以上
        data_loader = TwoBranchDataloader(
            main_data_loader=main_data_loader,
            auxiliary_data_loader=auxiliary_data_loader,
            **kwargs)
```

**Comment by guanlaoshi** [comment]
> Traceback (most recent call last): File "/root/mmfewshot/./tools/detection/train.py", line 236, in main() File "/root/mmfewshot/./tools/detection/train.py", line 225, in main train_detector( File "/root/mmfewshot/mmfewshot/detection/apis/train.py", line 48, in train_detector data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset] File "/root/mmfewshot/mmfewshot/detection/apis/train.py", line 48, in data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset] File "/root/mmfewshot/mmfewshot/detection/datasets/builder.py", line 311, in build_dataloader data_loader = TwoBranchDataloader( TypeError: **init**() got an unexpected keyword argument 'persistent_workers' Killing subprocess 9272 Traceback (most recent call last): File "/opt/conda/envs/pytorch1.8/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/opt/conda/envs/pytorch1.8/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in main() File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main sigkill_handler(signal.SIGTERM, None) # not coming back File "/opt/conda/envs/pytorch1.8/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd) subprocess.CalledProcessError: Command '['/opt/conda/envs/pytorch1.8/bin/python', '-u', './tools/detection/train.py', '--local_rank=0', 'configs/detection/mpsr/voc/split1/mpsr_r101_fpn_2xb2_voc-split1_base-training.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

可以在mmfewshot/detection/datasets/builder.py 第311行左右添加如下代码：
```python
        # wrap two dataloaders with dataloader wrapper
        #----------20230321添加以下
        #由于会出现TypeError: __init__() got an unexpected keyword argument 'persistent_workers'
        #所以在这删掉persistent_workers关键对
        del kwargs['persistent_workers']
        # ----------20230321添加以上
        data_loader = TwoBranchDataloader(
            main_data_loader=main_data_loader,
            auxiliary_data_loader=auxiliary_data_loader,
            **kwargs)
```
