### ISSUE TITLE
Error when plotting image recognition results

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmfewshot#13]
First of all kudos for the great repo!

There is a small problem with plotting the results [here](https://github.com/open-mmlab/mmfewshot/blob/217aff67f7b57cc5961633e3521318e3dd671174/mmfewshot/classification/apis/inference.py#L131). When running the image demo `demo_metric_classifier_1shot_inference` for the sample classes the following error occurs:

```
Traceback (most recent call last):
  File "demo/demo_metric_classifier_1shot_inference.py", line 51, in <module>
    main()
  File "demo/demo_metric_classifier_1shot_inference.py", line 47, in main
    show_result_pyplot(args.image, result)
  File "mmfewshot/mmfewshot/classification/apis/inference.py", line 150, in show_result_pyplot
    img = imshow_infos(
  File "mmfewshot/lib/python3.8/site-packages/mmcls/core/visualization/image.py", line 316, in imshow_infos
    img = manager.put_img_infos(
  File "/home/user/.pyenv/versions/mmfewshot/lib/python3.8/site-packages/mmcls/core/visualization/image.py", line 277, in put_img_infos
    self.wait_continue(timeout=wait_time)
  File "/home/user/.pyenv/versions/mmfewshot/lib/python3.8/site-packages/mmcls/core/visualization/image.py", line 138, in wait_continue
    key_press = self.blocking_input(n=1, timeout=0)
  File "/home/user/.pyenv/versions/mmfewshot/lib/python3.8/site-packages/matplotlib/blocking_input.py", line 86, in __call__
    if self.figure.canvas.manager:
AttributeError: 'BlockingInput' object has no attribute 'figure'
```

**Comment by linyq17** [comment]
I tried this command which can lead to expected results without error. And the plotting codes are directly imported from `mmcls`.
Can you provide more information about your runtime environment?

**Comment by rlleshi** [comment]
I downgraded `matplotlib` from `3.5.0` to `3.4.3`, which was the version that I had on `mmcls` and it solved the problem.
