### ISSUE TITLE
tools/classification/test.py has no attribute 'out'

### ISSUE THREAD

**Issue by YiDanCheung** [open-mmlab/mmfewshot#143]
root@autodl-container-4d7142bb21-b5d6d5d1:~/mmfewshot# python ./tools/classification/test.py \
>   configs/classification/baseline/cub/baseline_conv4_1xb64_cub_5way-1shot.py \
>   work_dir/baseline_conv4_1xb64_cub_5way-1shot/best_accuracy_mean.pth
Traceback (most recent call last):
  File "./tools/classification/test.py", line 200, in <module>
    main()
  File "./tools/classification/test.py", line 101, in main
    args = parse_args()
  File "./tools/classification/test.py", line 95, in parse_args
    assert args.metrics or args.out, \
AttributeError: 'Namespace' object has no attribute 'out'

**Comment by YiDanCheung** [comment]
https://github.com/open-mmlab/mmfewshot/tree/main/configs/classification/baseline/README.md的#meta testing的work_dir应为work_dirs
