### ISSUE TITLE
OSError: work_dir/relation-net_conv4_1xb105_cub_5way-1shot/best_accuracy_mean.pth is not a checkpoint file

### ISSUE THREAD

**Issue by YiDanCheung** [open-mmlab/mmfewshot#148]
1. base training:`python ./tools/classification/train.py configs/classification/relation_net/cub/relation-net_conv4_1xb105_cub_5way-1shot.py`

2. meta testing:`python ./tools/classification/test.py configs/classification/relation_net/cub/relation-net_conv4_1xb105_cub_5way-1shot.py work_dir/relation-net_conv4_1xb105_cub_5way-1shot/best_accuracy_mean.pth --metrics  accuracy`

3. Here is the error information :
load checkpoint from local path: work_dir/relation-net_conv4_1xb105_cub_5way-1shot/best_accuracy_mean.pth
Traceback (most recent call last):
  File "./tools/classification/test.py", line 200, in <module>
    main()
  File "./tools/classification/test.py", line 161, in main
    load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/home/sqjin/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 531, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/sqjin/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/sqjin/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/sqjin/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 265, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')

The same error occurs when i try to download [the official checkpoint file](https://download.openmmlab.com/mmfewshot/classification/relation_net/cub/relation-net_conv4_1xb105_cub_5way-1shot_20211120_101425-63bfa087.pth).

**Comment by YiDanCheung** [comment]
the problem solved following this [issue](https://github.com/open-mmlab/mmdetection/issues/1378#issuecomment-532285950)

**Comment by YiDanCheung** [comment]
`work_dir` should be `work_dirs`
