### ISSUE TITLE
Can't install mmfewshot correctly with openmim

### ISSUE THREAD

**Issue by genghisun** [open-mmlab/mmfewshot#22]
```
$ pip install openmim
$ mim install mmfewshot
$ mim list

Package    Version    Source
---------  ---------  --------

$ python demo/demo_metric_classifier_1shot_inference.py \
    demo/demo_classification_images/query_images/Least_Auklet.jpg \
    configs/classification/proto_net/cub/proto-net_conv4_1xb105_cub_5way-1shot.py \
    https://download.openmmlab.com/mmfewshot/classification/proto_net/cub/proto-net_conv4_1xb105_cub_5way-1shot_20211120_101211-9ab530c3.pth \
    --support-images-dir demo/demo_classification_images/support_images

Traceback (most recent call last):
  File "demo/demo_metric_classifier_1shot_inference.py", line 14, in <module>
    from mmfewshot.classification.apis import (inference_classifier,
  File "/miniconda3/envs/mmfewshot/lib/python3.8/site-packages/mmfewshot/__init__.py", line 2, in <module>
    import mmcls  # noqa: F401, F403
ModuleNotFoundError: No module named 'mmcls'
```

**Comment by linyq17** [comment]
Thank you very much for your feedback, we will fix it as soon as possible.
