### ISSUE TITLE
About the miniimagenet

### ISSUE THREAD

**Issue by xiaofeng-c** [open-mmlab/mmfewshot#51]
Thank you for yourcontribution,after get the format of miniimage dataset,i train it,but a error occurs as follow:
2022-03-04 18:21:39,431 - mmfewshot - INFO - Set random seed to 0, deterministic: False
Traceback (most recent call last):
  File "/home/dio/VSST/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/classification/datasets/mini_imagenet.py", line 73, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/classification/datasets/base.py", line 45, in __init__
    self.data_infos = self.load_annotations()
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/classification/datasets/mini_imagenet.py", line 140, in load_annotations
    int(filename.split('.')[0][-5:]) - 1]
IndexError: list index out of range
do you know what wrong with it?

**Comment by xiaofeng-c** [comment]
The picture format of original miniimage dataset just like 0153282900005.jpg，i try to get the format of n01532829_5.jpg according to the guidance.

**Comment by jshilong** [comment]
@linyq17 Would you mind taking a look at this issue?

**Comment by linyq17** [comment]
Currently, we read images directly from the original ImageNet. To adapt to a format like 0153282900005.jpg, the code needs some modifications.

**Comment by xiaofeng-c** [comment]
Ok,thank you,that means we must use the whole ImageNet dataset？

**Comment by Leeinsn** [comment]
> 

don't need! Just delete some code!

**Comment by Troyella** [comment]
can I ask where should I delete?

**Comment by BradSteven** [comment]
我遇到了相同的问题
2023-05-10 20:02:44,435 - mmfewshot - INFO - Set random seed to 0, deterministic: False
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\mmdet\lib\site-packages\mmcv\utils\registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/classification/train.py", line 187, in <module>
    main()
  File "./tools/classification/train.py", line 162, in main
    datasets = [build_dataset(cfg.data.train)]
  File "d:\upload\pyworkspace\few-shot learning\mmfewshot-main\mmfewshot\classification\datasets\builder.py", line 29, in build_dataset
    build_dataset(cfg['dataset'], default_args),
  File "d:\upload\pyworkspace\few-shot learning\mmfewshot-main\mmfewshot\classification\datasets\builder.py", line 45, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "D:\ProgramData\Anaconda3\envs\mmdet\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
IndexError: MiniImageNetDataset: list index out of range

**Can someone tell me where the boundary has been crossed？？Which number should I change？**

**Comment by YiDanCheung** [comment]
> > 
> 
> don't need! Just delete some code!

当删除掉`mmfewshot/classification/datasets/mini_imagenet.py`Line 118（`img_file_list`的初始化代码）以及Line 135（`filename = img_file_list[class_name][int(filename.split('.')[0][-5:]) - 1]`）后确实可以运行，但是我不知道这是为什么
