### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by xiaofeng-c** [open-mmlab/mmfewshot#55]
when train with my own datasets,a problem occur as follow:
Traceback (most recent call last):
  File "/home/dio/VSST/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/detection/datasets/voc.py", line 132, in __init__
    **kwargs)
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/detection/datasets/base.py", line 140, in __init__
    self.data_infos = self.ann_cfg_parser(ann_cfg)
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/detection/datasets/base.py", line 279, in ann_cfg_parser
    return self.load_annotations(ann_cfg)
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/detection/datasets/voc.py", line 223, in load_annotations
    ann_cfg_['ann_file'], ann_classes)
  File "/home/dio/VSST/zwm/mmfewshot/mmfewshot/detection/datasets/voc.py", line 279, in load_annotations_xml
    tree = ET.parse(xml_path)
  File "/home/dio/VSST/anaconda3/envs/openmmlab/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/home/dio/VSST/anaconda3/envs/openmmlab/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

do you know what wrong with it?thank you!

**Comment by xiaofeng-c** [comment]
I have tackled it,it caused by the wrong format of dataset.

**Comment by lnq325805524** [comment]
Hello. Could you please share the script to prepare the dataset?
